name: indiabana_app
version: 0.1.0
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  get: 4.6.5
  flutter:
    sdk: flutter
  logger: ^2.0.1
  dio: ^5.3.1
  intl: 0.18.0
  get_it: ^7.6.0
  get_storage: ^2.1.1
  carousel_slider: ^4.2.1
  cached_network_image: ^3.2.3
  flutter_rating_bar: ^4.0.1
  scroll_to_index: ^3.0.1
  image_picker: ^1.0.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
